---
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: false
  RequireScriptNonce:
    enabled: false
  PartialInstanceVariable:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Style/QuotedSymbols:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/RedundantPercentQ:
        Enabled: false
      Style/StringLiterals:
        Enabled: false
      Style/StringConcatenation:
        Enabled: false # This is disabled so we can concatenate tags to avoid using html_safe.
      BestPractices/RequireExplanationWhenDisabling:
        Enabled: false
      BestPractices/NoInstanceVariablesInViews:
        Enabled: true
